### ISSUE TITLE
Unable to startup bitbake server

### ISSUE THREAD

**Issue by budebulai** [crops/poky-container#44]
On my PC, 
- Docker for Windows installed, 
- a portable hard disk shared to docker, such as drive I
- poky downloaded at drive I:/WORKSPACE/yocto3-ws

In PowerShell console, running command
`docker run -it --name yocto-ws --mount type=bind,source=I:/WORKSPACE,target=/workdir crops/poky`, yocto-ws container can start up. Everything is ok until now.

But when running `bitbake core-image-minimal` in poky build dir, something wrong, 
_**server = bb.server.process.BitBakeServer(lock, sockname, configuration, featureset)
  File "/workdir/yocto3_ws/poky/bitbake/lib/bb/server/process.py", line 392, in __init__
    self.sock.bind(os.path.basename(sockname))
PermissionError: [Errno 1] Operation not permitted
......
NOTE: Reconnecting to bitbake server...
NOTE: Previous bitbake instance shutting down?, waiting to retry...
NOTE: Retrying server connection (#8)...
ERROR: Unable to connect to bitbake server, or start one (server startup failures would be in bitbake-cookerdaemon.log).**_

And when `./x86_64-buildtools-nativesdk-standalone-3.0.1.sh` script execution tried, also error occured,
**_Build tools installer version 3.0.1
Enter target directory for SDK (default: /opt/poky/3.0.1): /workdir/yocto3_ws/buildtools
You are about to install the SDK to "/workdir/yocto3_ws/buildtools". Proceed [Y/n]? Y
Extracting SDK...........done
Setting it up...Traceback (most recent call last):
  File "/workdir/yocto3_ws/buildtools/relocate_sdk.py", line 219, in <module>
    perms = os.stat(e)[stat.ST_MODE]
OSError: [Errno 2] No such file or directory: '/workdir/yocto3_ws/buildtools/sysroots/x86_64-pokysdk-linux/usr/bin/find'
SDK could not be set up. Relocate script failed. Abort!_**

What's wrong with crops/poky? 
Howto?

**Comment by rewitt1** [comment]
Hi @budebulai,

Does the problem still occur if you instead use a _volume_ following the instructions on the [wiki](https://github.com/crops/docker-win-mac-docs/wiki/Windows-Instructions-%28Docker-Toolbox%29#create-the-samba-container)?

bitbake requires a filesystem with capabilities similar to ext4 and other linux filesystems. Running docker as you outlined above would use the a virtual filesystem to map the filesystem of _I:_ to the VM used by docker for windows.

I don't have a windows machine to test this with currently, but this would be my first guess.
